#!/bin/bash
BASE="/home/ubuntu/hbb/content/en/perfumes"

create_subcat() {
    local slug="$1" title="$2" desc="$3" type="$4" value="$5" emoji="$6"
    mkdir -p "$BASE/$slug"
    cat > "$BASE/$slug/_index.md" << EOF
---
title: "$title"
description: "$desc"
emoji: "$emoji"
subcategory_type: "$type"
subcategory_value: "$value"
---
EOF
    echo "  ✓ $slug"
}

echo "=== GENDER (3) ==="
create_subcat "women" "Women's Perfumes" "Discover our curated collection of the finest women's fragrances." "gender" "Women" "👩"
create_subcat "men" "Men's Perfumes" "Explore our selection of distinguished men's fragrances." "gender" "Men" "👨"
create_subcat "unisex" "Unisex Perfumes" "Browse our collection of gender-neutral fragrances." "gender" "Unisex" "⚧️"

echo "=== FAMILY (7) ==="
create_subcat "floral" "Floral Perfumes" "Explore our collection of floral fragrances, from delicate rose to exotic jasmine." "family" "floral" "🌸"
create_subcat "oriental" "Oriental Perfumes" "Discover rich oriental fragrances with warm notes of vanilla, amber, and spices." "family" "oriental" "🌙"
create_subcat "woody" "Woody Perfumes" "Browse our woody fragrance collection featuring sandalwood, cedar, and vetiver." "family" "woody" "🌲"
create_subcat "fresh" "Fresh Perfumes" "Discover invigorating fresh fragrances with citrus, aquatic, and green notes." "family" "fresh" "🍃"
create_subcat "aromatic" "Aromatic Perfumes" "Explore aromatic fragrances blending herbs, lavender, and spices." "family" "aromatic" "🌿"
create_subcat "chypre" "Chypre Perfumes" "Discover the elegant world of chypre fragrances, built on oakmoss and bergamot." "family" "chypre" "🍂"
create_subcat "gourmand" "Gourmand Perfumes" "Indulge in delicious gourmand fragrances with vanilla, chocolate, and coffee." "family" "gourmand" "🍫"

echo "=== SUBFAMILY (32) ==="
create_subcat "floral-fruity" "Floral Fruity Perfumes" "Vibrant floral fruity fragrances blending flower petals with juicy fruit notes." "subfamily" "floral-fruity" "🌸"
create_subcat "floral-white" "White Floral Perfumes" "Intoxicating white floral fragrances featuring jasmine, tuberose, and gardenia." "subfamily" "floral-white" "🤍"
create_subcat "floral-powdery" "Floral Powdery Perfumes" "Soft and elegant floral powdery fragrances with iris, violet, and heliotrope." "subfamily" "floral-powdery" "💜"
create_subcat "floral-green" "Floral Green Perfumes" "Fresh floral green fragrances blending garden flowers with crisp green notes." "subfamily" "floral-green" "🌱"
create_subcat "floral-aldehyde" "Floral Aldehyde Perfumes" "Classic floral aldehyde fragrances, the foundation of timeless perfumery." "subfamily" "floral-aldehyde" "✨"
create_subcat "floral-aquatic" "Floral Aquatic Perfumes" "Refreshing floral aquatic fragrances blending flowers with ocean-inspired notes." "subfamily" "floral-aquatic" "🌊"
create_subcat "oriental-spicy" "Oriental Spicy Perfumes" "Bold oriental spicy fragrances with cinnamon, cardamom, and pepper." "subfamily" "oriental-spicy" "🌶️"
create_subcat "oriental-vanilla" "Oriental Vanilla Perfumes" "Warm and sensual oriental vanilla fragrances, perfect for evening wear." "subfamily" "oriental-vanilla" "🍦"
create_subcat "oriental-amber" "Oriental Amber Perfumes" "Rich amber fragrances with warm, resinous notes of benzoin and labdanum." "subfamily" "oriental-amber" "🔶"
create_subcat "oriental-woody" "Oriental Woody Perfumes" "The fusion of eastern spices and noble woods in oriental woody fragrances." "subfamily" "oriental-woody" "🪵"
create_subcat "oriental-floral" "Oriental Floral Perfumes" "Exotic oriental floral fragrances blending Eastern mystique with flower elegance." "subfamily" "oriental-floral" "🌺"
create_subcat "woody-aromatic" "Woody Aromatic Perfumes" "Woody aromatic fragrances combining noble woods with fresh herbs and spices." "subfamily" "woody-aromatic" "🌿"
create_subcat "woody-spicy" "Woody Spicy Perfumes" "Bold woody spicy fragrances with cedar, pepper, and warm spice notes." "subfamily" "woody-spicy" "🔥"
create_subcat "woody-dry" "Woody Dry Perfumes" "Refined dry woody fragrances featuring vetiver, cedar, and sandalwood." "subfamily" "woody-dry" "🏜️"
create_subcat "woody-mossy" "Woody Mossy Perfumes" "Earthy woody mossy fragrances with oakmoss, patchouli, and forest notes." "subfamily" "woody-mossy" "🌳"
create_subcat "woody-earthy" "Woody Earthy Perfumes" "Grounding earthy woody fragrances with oud, patchouli, and incense." "subfamily" "woody-earthy" "🍄"
create_subcat "fresh-citrus" "Citrus Perfumes" "Bright and zesty citrus fragrances with bergamot, lemon, and grapefruit." "subfamily" "fresh-citrus" "🍋"
create_subcat "fresh-aquatic" "Aquatic Perfumes" "Refreshing aquatic fragrances inspired by ocean breezes and sea spray." "subfamily" "fresh-aquatic" "🌊"
create_subcat "fresh-green" "Green Perfumes" "Crisp green fragrances with galbanum, fig leaf, and fresh-cut grass." "subfamily" "fresh-green" "🍃"
create_subcat "fresh-ozonic" "Ozonic Perfumes" "Clean and airy ozonic fragrances evoking rain, sky, and mountain air." "subfamily" "fresh-ozonic" "💨"
create_subcat "fresh-fruity" "Fresh Fruity Perfumes" "Playful fresh fruity fragrances with peach, apple, pear, and berry notes." "subfamily" "fresh-fruity" "🍑"
create_subcat "aromatic-fougere" "Fougère Perfumes" "Classic fougère fragrances built on lavender, oakmoss, and coumarin." "subfamily" "aromatic-fougere" "🌾"
create_subcat "aromatic-herbal" "Herbal Perfumes" "Fresh herbal fragrances with rosemary, thyme, sage, and mint." "subfamily" "aromatic-herbal" "🌿"
create_subcat "aromatic-spicy" "Aromatic Spicy Perfumes" "Aromatic spicy fragrances blending herbs with warm pepper and ginger." "subfamily" "aromatic-spicy" "🫚"
create_subcat "aromatic-marine" "Marine Perfumes" "Fresh marine fragrances with sea salt, seaweed, and ocean air notes." "subfamily" "aromatic-marine" "⛵"
create_subcat "chypre-fruity" "Chypre Fruity Perfumes" "Elegant chypre fruity fragrances combining citrus with oakmoss and fruits." "subfamily" "chypre-fruity" "🍊"
create_subcat "chypre-floral" "Chypre Floral Perfumes" "Sophisticated chypre floral fragrances with rose, jasmine, and oakmoss." "subfamily" "chypre-floral" "🌹"
create_subcat "chypre-leather" "Chypre Leather Perfumes" "Bold chypre leather fragrances with suede, birch tar, and smoky notes." "subfamily" "chypre-leather" "🧥"
create_subcat "chypre-green" "Chypre Green Perfumes" "Fresh chypre green fragrances with galbanum, moss, and herbal notes." "subfamily" "chypre-green" "🍀"
create_subcat "gourmand-vanilla" "Gourmand Vanilla Perfumes" "Decadent gourmand vanilla fragrances with rich, creamy, and sweet notes." "subfamily" "gourmand-vanilla" "🍨"
create_subcat "gourmand-sweet" "Sweet Perfumes" "Irresistible sweet fragrances with caramel, toffee, and praline notes." "subfamily" "gourmand-sweet" "🍬"
create_subcat "gourmand-coffee" "Coffee Perfumes" "Rich coffee fragrances with espresso, mocha, and roasted bean notes." "subfamily" "gourmand-coffee" "☕"
create_subcat "gourmand-chocolate" "Chocolate Perfumes" "Indulgent chocolate fragrances with cocoa, dark chocolate, and truffle notes." "subfamily" "gourmand-chocolate" "🍫"

echo "=== OCCASION (9) ==="
create_subcat "everyday" "Everyday Perfumes" "Find your perfect everyday fragrance — versatile scents for daily wear." "occasion" "Everyday" "☀️"
create_subcat "evening" "Evening Perfumes" "Captivating evening fragrances that make a lasting impression after dark." "occasion" "Evening" "🌃"
create_subcat "romantic" "Romantic Perfumes" "Seductive romantic fragrances for date nights and special occasions." "occasion" "Romantic" "💕"
create_subcat "office" "Office Perfumes" "Professional office fragrances that are refined, subtle, and workplace-appropriate." "occasion" "Office" "💼"
create_subcat "summer" "Summer Perfumes" "Refreshing summer fragrances with light, breezy notes for warm weather." "occasion" "Summer" "🏖️"
create_subcat "winter" "Winter Perfumes" "Warm and cozy winter fragrances with rich, enveloping notes for cold days." "occasion" "Winter" "❄️"
create_subcat "wedding" "Wedding Perfumes" "Find the perfect wedding fragrance for your special day." "occasion" "Wedding" "💒"
create_subcat "sport" "Sport Perfumes" "Energizing sport fragrances that keep you fresh during active pursuits." "occasion" "Sport" "🏃"
create_subcat "travel" "Travel Perfumes" "Travel-friendly fragrances perfect for adventurers and jet-setters." "occasion" "Travel" "✈️"

echo ""
echo "=== TOTAL ==="
find "$BASE" -name "_index.md" -not -path "$BASE/_index.md" | wc -l
echo "subcategory files created"
